name: no-ent.re
favicon: null
layout_spectrum: 0.9302175445482135
typography_spectrum: 0.8635652961675078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.016473075142130256
  lightness: 0.09172252006828785
  saturation: 0.014773098286241293
  rhythmicContrast: 0.9270671457052231
purpose: []
